include("shared.lua")

include("client/menus/cl_new_player.lua")
include("client/achievements/cl_ach_base.lua")
include("client/menus/cl_f4_menu.lua")
include("client/menus/cl_difficulty_vote.lua")
include("client/menus/cl_scoreboard.lua")
include("client/cl_hud.lua")
include("client/menus/cl_pets.lua")
include("client/menus/cl_new_player.lua")
include("client/menus/cl_squads.lua")
include("client/menus/cl_otf.lua")