include("shared.lua")

include("client/menus/cl_new_player.lua")
include("client/achievements/cl_ach_base.lua")
include("client/menus/cl_f4_menu.lua")
include("client/menus/cl_difficulty_vote.lua")
include("client/menus/cl_scoreboard.lua")
include("client/cl_hud.lua")
include("client/menus/cl_new_player.lua")
include("client/menus/cl_otf.lua")

include("client/menus/cl_pets.lua")
include("client/menus/pets/cl_headcrab.lua")
include("client/menus/pets/cl_torsozombie_tree.lua")
include("client/menus/pets/cl_zombie_tree.lua")
include("client/menus/pets/cl_fast_headcrab_tree.lua")
include("client/menus/pets/cl_fast_torso_tree.lua")
include("client/menus/pets/cl_fast_zombie_tree.lua")
include("client/menus/pets/cl_rollermine.lua")
include("client/menus/pets/cl_manhack.lua")
include("client/menus/pets/cl_stalker.lua")
include("client/menus/pets/cl_metropolice_stunstuck.lua")
include("client/menus/pets/cl_metropolice_pistol.lua")
include("client/menus/pets/cl_metropolice_smg.lua")

include("client/menus/cl_ui.lua")
include("client/menus/cl_fonts.lua")
include("client/menus/cl_prestige.lua")
