--New player
util.AddNetworkString("Greetings_new_player")
--Open menus and commands
util.AddNetworkString("Open_Ach_Menu")
util.AddNetworkString("Open_F4_Menu")
--Data management
util.AddNetworkString("Create_Data")
util.AddNetworkString("Achievement_Earned")
util.AddNetworkString("Achievement")
util.AddNetworkString("Special_Earned")
util.AddNetworkString("Update_Model")

util.AddNetworkString("SetSuicide")
util.AddNetworkString("Open_Diff_Menu")
util.AddNetworkString("Diff_Vote")
util.AddNetworkString("Diff_Change")
util.AddNetworkString("Survival")
util.AddNetworkString("SurvAllDead")
util.AddNetworkString("RefreshVote")
util.AddNetworkString("GiveXPAndCoins")
util.AddNetworkString("IndicSpawn")
util.AddNetworkString("PlaySoundLevelUp")
util.AddNetworkString("DisplayMapTimer")
util.AddNetworkString("ReturnLobby")
util.AddNetworkString("DollAch")
util.AddNetworkString("NewSuit")
util.AddNetworkString("DisplayRewards")
util.AddNetworkString("Spectating")
util.AddNetworkString("Open_Pet_Menu")
util.AddNetworkString("UpdatePetsBool")
util.AddNetworkString("UpdatePetsSkill")
util.AddNetworkString("SpawnPetConCommand")
util.AddNetworkString("ClosePets")
util.AddNetworkString("OpenPetStats")
util.AddNetworkString("UpdatePetsHealth")
util.AddNetworkString("UpdatePetsHealthDMG")
util.AddNetworkString("CommandPetXP")
util.AddNetworkString("PetDuel")
util.AddNetworkString("PetChallenge")
util.AddNetworkString("UpdateSkillPoints")
util.AddNetworkString("UpdateSkills")
util.AddNetworkString("Evolving")
util.AddNetworkString("NewPet")
util.AddNetworkString("PetDead")
util.AddNetworkString("IndicPetSpawn")
util.AddNetworkString("PetKilled")
util.AddNetworkString("WarningPetKill")
util.AddNetworkString("KickUser")
util.AddNetworkString("PetPanic")
--Shops
util.AddNetworkString("Purchase")
util.AddNetworkString("Exchange")
util.AddNetworkString("Upgrade")
util.AddNetworkString("SellItem")
util.AddNetworkString("SellItemSlot")

--Inventory
util.AddNetworkString("AddArmour")

--Squads and Combine Loyals
util.AddNetworkString("Squad_Created")
util.AddNetworkString("Squad_Disband")
util.AddNetworkString("Squad_XPUpdate")
util.AddNetworkString("Squad_Joined")
util.AddNetworkString("Squad_Left")

--End map
util.AddNetworkString("ShowEndStats")