util.AddNetworkString( "Open_Ach_Menu" )
util.AddNetworkString( "Greetings_new_player" )
util.AddNetworkString( "Create_Data" )
util.AddNetworkString( "Open_F4_Menu" )
util.AddNetworkString("Achievement_Earned")
util.AddNetworkString("Achievement")
util.AddNetworkString("Update_Model")
util.AddNetworkString("Failed_Command")
util.AddNetworkString("GiveXP")