pac_hatModel = {}

pac_hatModel[ "BabyHead" ] = {
	[1] = {
		["children"] = {
			[1] = {
				["children"] = {
					[1] = {
						["children"] = {
						},
						["self"] = {
							["DrawOrder"] = 0,
							["UniqueID"] = "671740118",
							["OwnerName"] = "self",
							["AimPartName"] = "",
							["Bone"] = "head",
							["Position"] = Vector(0.7392578125, 0.03515625, 6.4644165039063),
							["AimPartUID"] = "",
							["Hide"] = false,
							["Name"] = "",
							["AngleOffset"] = Angle(0, 0, 0),
							["EditorExpand"] = false,
							["EyeAngles"] = false,
							["PositionOffset"] = Vector(0, 0, 0),
							["IsDisturbing"] = false,
							["ClassName"] = "clip",
							["Translucent"] = false,
							["Angles"] = Angle(-62.850193023682, -0.00091304956004024, 0.00031198977376334),
						},
					},
				},
				["self"] = {
					["Skin"] = 0,
					["Invert"] = false,
					["LightBlend"] = 1,
					["CellShade"] = 0,
					["OwnerName"] = "self",
					["AimPartName"] = "",
					["IgnoreZ"] = false,
					["AimPartUID"] = "",
					["Passes"] = 1,
					["Name"] = "",
					["NoTextureFiltering"] = false,
					["DoubleFace"] = false,
					["PositionOffset"] = Vector(0, 0, 0),
					["IsDisturbing"] = false,
					["Fullbright"] = false,
					["EyeAngles"] = false,
					["DrawOrder"] = 0,
					["TintColor"] = Vector(0, 0, 0),
					["UniqueID"] = "3758072358",
					["Translucent"] = false,
					["LodOverride"] = -1,
					["BlurSpacing"] = 0,
					["Alpha"] = 1,
					["Material"] = "",
					["UseWeaponColor"] = false,
					["UsePlayerColor"] = false,
					["UseLegacyScale"] = false,
					["Bone"] = "head",
					["Color"] = Vector(255, 255, 255),
					["Brightness"] = 1,
					["BoneMerge"] = false,
					["BlurLength"] = 0,
					["Position"] = Vector(-9.7745971679688, -0.35546875, 0.1416015625),
					["AngleOffset"] = Angle(0, 0, 0),
					["AlternativeScaling"] = false,
					["Hide"] = false,
					["OwnerEntity"] = false,
					["Scale"] = Vector(1, 1, 1),
					["ClassName"] = "model",
					["EditorExpand"] = true,
					["Size"] = 2.5,
					["ModelFallback"] = "",
					["Angles"] = Angle(-1.7932021617889, -85.872940063477, -90.560081481934),
					["TextureFilter"] = 3,
					["Model"] = "models/props_c17/doll01.mdl",
					["BlendMode"] = "",
				},
			},
		},
		["self"] = {
			["DrawOrder"] = 0,
			["UniqueID"] = "1258053841",
			["AimPartUID"] = "",
			["Hide"] = false,
			["Duplicate"] = false,
			["ClassName"] = "group",
			["OwnerName"] = "self",
			["IsDisturbing"] = false,
			["Name"] = "my outfit",
			["EditorExpand"] = true,
		},
	},
}
